#!/usr/bin/env bash
# Emit the mode-parity LIVENESS fixture: non-tail freeze-time recursion.
# Depth is a fixture parameter, not an assertion. 1000 reddened `wat --check`
# with 134 (SIGABRT) and left the run path at 0 on this machine (2026-09-05).
# A tail-call chain does not overflow; each step is `i64::+ 0 (f_{i+1})`.
set -euo pipefail
DEPTH="${1:-1000}"
echo ";; generated by tests/cli/gen_mode_parity_deep.sh ${DEPTH}"
echo ";; Do not load in-process. Drive as a wat subprocess only."
echo "(:wat::core::defn :user::f${DEPTH} [] -> :wat::core::i64 0)"
i=$((DEPTH - 1))
while [ "$i" -ge 0 ]; do
  echo "(:wat::core::defn :user::f${i} [] -> :wat::core::i64 (:wat::core::i64::+ 0 (:user::f$((i + 1)))))"
  i=$((i - 1))
done
echo "(:wat::core::def :user::deep (:user::f0))"
echo "(:wat::core::defn :user::main [] -> :wat::core::nil"
echo "  (:wat::kernel::println \"deep-ok\"))"
