//! Integration test root for `src/distribution/` (the `wat` / `cargo-wat`
//! binaries — arc 170 folded this group in from the former `wat-cli`
//! crate's `tests/wat_cli.rs`).
//!
//! Tests organized to mirror src/ directory structure (convention started
//! 2026-05-19 with arc 214 Slice 3). The `mod.rs` root + sub-files pattern
//! is the idiomatic Rust way to group related integration tests:
//!
//!   - `tests/cli/mod.rs` is the crate root for the cli test binary
//!     (registered in Cargo.toml via a single `[[test]] name = "cli"
//!     path = "tests/cli/mod.rs"` entry)
//!   - the sub-files are brought in by build.rs (see below)
//!   - all cli tests share one binary (one link)
//!   - filter via `cargo test --test cli <path>::` — e.g.,
//!     `cargo test --test cli wat_cli::` runs only the wat_cli.rs group
//!
//! Adding a group: `tests/<group>/mod.rs` (this `include!` stub) + one
//! `[[test]]` Cargo.toml entry. Adding a test to a group: just drop the `.rs`
//! file in — build.rs lists it automatically; there is no mod list to edit.
//!
//! The module list is GENERATED by build.rs into OUT_DIR — drop a `.rs` here and
//! it is compiled + run on the next `cargo test`; no manual step, no drift gate.
include!(concat!(env!("OUT_DIR"), "/cli_mods.rs"));
