//! Mode-parity gate: `--check` vs the run path, driving the real `wat` binary
//! as a subprocess (`DESIGN.md` strike-mode-parity).
//!
//! "Agree" is not "same exit code." `--check` exits 1 on freeze failure where
//! the run path exits 3; that difference is by design. The invariant:
//!
//! - SOUNDNESS — `--check` Accepted ⇒ the run path does not Reject
//!   (does not fail before `:user::main`)
//! - LIVENESS  — run Accepted ⇒ `--check` does not die by signal
//!
//! RED at HEAD on both arms is the deliverable. A green gate is a failed strike.
//! The same implications are GREEN under a stub of their own cure (see the
//! mutation tests). No `src/` change. No cure. No depth constant in an assertion.
//!
//! The deep fixture lives beside this file as a `.wat` (generated by
//! `gen_mode_parity_deep.sh`). Drive it as a subprocess only — never
//! `startup_from_source` it in-process.

use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_wat")
}

/// Three arms. Not an exit-code table. `None` from `ExitStatus::code()` is a signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Outcome {
    Accepted,
    Rejected,
    DiedBySignal(i32),
}

fn classify(status: ExitStatus) -> Outcome {
    match status.code() {
        Some(0) => Outcome::Accepted,
        Some(_) => Outcome::Rejected,
        None => {
            #[cfg(unix)]
            {
                use std::os::unix::process::ExitStatusExt;
                Outcome::DiedBySignal(status.signal().unwrap_or(0))
            }
            #[cfg(not(unix))]
            {
                Outcome::DiedBySignal(0)
            }
        }
    }
}

fn drive(args: &[&str], fixture: &Path) -> Outcome {
    let output = Command::new(bin())
        .args(args)
        .arg(fixture)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .unwrap_or_else(|e| panic!("spawn wat ({args:?} {fixture:?}): {e}"));
    classify(output.status)
}

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/cli")
        .join(name)
}

/// SOUNDNESS: `--check` Accepted ⇒ run is not Rejected.
fn soundness_holds(check: Outcome, run: Outcome) -> bool {
    if check == Outcome::Accepted {
        run != Outcome::Rejected
    } else {
        true
    }
}

/// LIVENESS: run Accepted ⇒ `--check` does not die by signal.
fn liveness_holds(check: Outcome, run: Outcome) -> bool {
    if run == Outcome::Accepted {
        !matches!(check, Outcome::DiedBySignal(_))
    } else {
        true
    }
}

struct Case {
    name: &'static str,
}

/// Non-vacuity: both arms and the control are named, and the files exist.
/// A fixed-size `!is_empty()` on a literal is not a guard; dropping a name is.
#[test]
fn mode_parity_cases_are_named() {
    let cases = [
        Case {
            name: "mode_parity__empty.wat",
        },
        Case {
            name: "mode_parity__deep_freeze_recursion.wat",
        },
        Case {
            name: "mode_parity__good.wat",
        },
    ];
    let names: Vec<&str> = cases.iter().map(|c| c.name).collect();
    assert_eq!(
        names,
        [
            "mode_parity__empty.wat",
            "mode_parity__deep_freeze_recursion.wat",
            "mode_parity__good.wat"
        ],
        "an arm's fixture was dropped or renamed — the gate is not covering that arm"
    );
    for c in &cases {
        let p = fixture(c.name);
        assert!(p.is_file(), "missing fixture {}", p.display());
        eprintln!("mode-parity case: {}", c.name);
    }
}

/// Two drives to fire and two to refuse before the arms. Shape from
/// `probe_vig_value_hash_collision` calibration.
#[test]
fn mode_parity_calibration() {
    let good = fixture("mode_parity__good.wat");
    let empty = fixture("mode_parity__empty.wat");
    let bad = fixture("wat_cli__check_bad.wat");
    assert_eq!(
        drive(&["--check"], &good),
        Outcome::Accepted,
        "FIRE 1: --check accepts a well-formed program"
    );
    assert_eq!(
        drive(&[], &good),
        Outcome::Accepted,
        "FIRE 2: run accepts a well-formed program"
    );
    assert_eq!(
        drive(&[], &empty),
        Outcome::Rejected,
        "REFUSE 1: run rejects a program with no :user::main"
    );
    assert_eq!(
        drive(&["--check"], &bad),
        Outcome::Rejected,
        "REFUSE 2: --check rejects a type-incorrect program"
    );
}

/// SOUNDNESS arm. Implication, not a monument: if `--check` Accepts, run
/// must not Reject. At HEAD the empty file violates it. After a correct
/// cure `--check` Rejects the empty file and the implication holds.
#[test]
fn mode_parity_empty() {
    let path = fixture("mode_parity__empty.wat");
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    eprintln!("HEAD empty: --check={check:?} run={run:?}");
    assert!(
        soundness_holds(check, run),
        "SOUNDNESS: --check Accepted but run Rejected before :user::main (check={check:?} run={run:?})"
    );
}

/// LIVENESS arm. Implication: if run Accepts, `--check` must not die by
/// signal. At HEAD the deep fixture violates it. After a correct cure
/// `--check` terminates normally and the implication holds.
#[test]
fn mode_parity_deep_freeze_recursion() {
    let path = fixture("mode_parity__deep_freeze_recursion.wat");
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    eprintln!("HEAD deep: --check={check:?} run={run:?}");
    assert!(
        liveness_holds(check, run),
        "LIVENESS: run terminated normally but --check died by signal (check={check:?} run={run:?})"
    );
}

/// CONTROL. Both modes Accept. If this row is red the gate does not discriminate.
#[test]
fn mode_parity_good() {
    let path = fixture("mode_parity__good.wat");
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    assert_eq!(
        check,
        Outcome::Accepted,
        "good --check must Accept; got {check:?}"
    );
    assert_eq!(run, Outcome::Accepted, "good run must Accept; got {run:?}");
    if check == Outcome::Accepted {
        assert_eq!(
            run,
            Outcome::Accepted,
            "SOUNDNESS on control: --check Accepted but run={run:?}"
        );
    }
    assert!(
        !matches!(check, Outcome::DiedBySignal(_)),
        "LIVENESS on control: --check died by signal {check:?}"
    );
}

/// Mutation: a stub of the SOUNDNESS cure (empty `--check` Rejects) greens
/// that arm only. The LIVENESS defect (signal death + run Accept) stays red.
#[test]
fn mode_parity_soundness_cure_greens_only_that_arm() {
    assert!(
        soundness_holds(Outcome::Rejected, Outcome::Rejected),
        "cured empty (--check Rejects) must satisfy SOUNDNESS"
    );
    assert!(
        !liveness_holds(Outcome::DiedBySignal(6), Outcome::Accepted),
        "SOUNDNESS cure must not green the LIVENESS defect"
    );
}

/// Mutation: a stub of the LIVENESS cure (deep `--check` Accepts) greens
/// that arm only. The SOUNDNESS defect (check Accept + run Reject) stays red.
#[test]
fn mode_parity_liveness_cure_greens_only_that_arm() {
    assert!(
        liveness_holds(Outcome::Accepted, Outcome::Accepted),
        "cured deep (--check Accepts) must satisfy LIVENESS"
    );
    assert!(
        !soundness_holds(Outcome::Accepted, Outcome::Rejected),
        "LIVENESS cure must not green the SOUNDNESS defect"
    );
}
