//! Mode-parity gate: `--check` vs the run path, driving the real `wat` binary
//! as a subprocess (`DESIGN.md` strike-mode-parity).
//!
//! "Agree" is not "same exit code." `--check` exits 1 on freeze failure where
//! the run path exits 3; that difference is by design. The invariant:
//!
//! - SOUNDNESS — `--check` Accepted ⇒ the run path does not reject it for a reason `--check`
//!   could itself have seen. A missing `:user::main` is the one EXCLUDED reason (narrowed at
//!   replay #388, BRIEF-7m-ADDENDUM-388, finding 40): `--check` is this tree's UNIT checker
//!   (`startup_from_source` deliberately allows a world with no entry point — library modules,
//!   `wat-scripts/` fixtures, `startup_bare()`), while the run path answers "is this a program I
//!   can start". A DECLARED but malformed main is still a real SOUNDNESS violation and must fail
//!   `--check` (see `mode_parity_malformed_main`).
//! - LIVENESS  — run Accepted ⇒ `--check` does not die by signal
//!
//! Landed here RED-then-cured: both arms were `#[ignore]`d red at #387 (assertions intact) and
//! un-ignored at #388 once the cure landed — the `RLIMIT_STACK` hoist verbatim (LIVENESS), and a
//! NARROWED entry-point check (SOUNDNESS: `validate_user_main_signature` runs only when
//! `:user::main` is actually declared — grok's own #388 ran it unconditionally, which on this
//! tree's corpus flipped `wat --check` to rc-non-zero on 1052 of 2165 tracked `.wat` files, most
//! of which are units with no entry point by design).
//!
//! The deep fixture lives beside this file as a `.wat` (generated by
//! `gen_mode_parity_deep.sh`). Drive it as a subprocess only — never
//! `startup_from_source` it in-process.

use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_wat")
}

/// Three arms. Not an exit-code table. `None` from `ExitStatus::code()` is a signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Outcome {
    Accepted,
    Rejected,
    DiedBySignal(i32),
}

fn classify(status: ExitStatus) -> Outcome {
    match status.code() {
        Some(0) => Outcome::Accepted,
        Some(_) => Outcome::Rejected,
        None => {
            #[cfg(unix)]
            {
                use std::os::unix::process::ExitStatusExt;
                Outcome::DiedBySignal(status.signal().unwrap_or(0))
            }
            #[cfg(not(unix))]
            {
                Outcome::DiedBySignal(0)
            }
        }
    }
}

fn drive(args: &[&str], fixture: &Path) -> Outcome {
    let output = Command::new(bin())
        .args(args)
        .arg(fixture)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .unwrap_or_else(|e| panic!("spawn wat ({args:?} {fixture:?}): {e}"));
    classify(output.status)
}

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/cli")
        .join(name)
}

/// SOUNDNESS, this tree's semantics (BRIEF-7m-ADDENDUM-388, finding 40): `--check` Accepted ⇒
/// the run path does not reject it for a reason `--check` could itself have seen. `has_main`
/// names the one EXCLUDED reason — a missing entry point is a MODE difference (`--check` answers
/// "does this unit type-check"; the run path answers "is this a program I can start"), not an
/// unsoundness. When `has_main` is true, a run Rejection is a genuine violation: `--check`
/// Accepted a program whose declared main the run path then refused for a reason `--check`
/// should have caught.
fn soundness_holds(check: Outcome, run: Outcome, has_main: bool) -> bool {
    if check == Outcome::Accepted {
        run != Outcome::Rejected || !has_main
    } else {
        true
    }
}

/// LIVENESS: run Accepted ⇒ `--check` does not die by signal.
fn liveness_holds(check: Outcome, run: Outcome) -> bool {
    if run == Outcome::Accepted {
        !matches!(check, Outcome::DiedBySignal(_))
    } else {
        true
    }
}

struct Case {
    name: &'static str,
}

/// Non-vacuity: both arms and the control are named, and the files exist.
/// A fixed-size `!is_empty()` on a literal is not a guard; dropping a name is.
#[test]
fn mode_parity_cases_are_named() {
    let cases = [
        Case {
            name: "mode_parity__empty.wat",
        },
        Case {
            name: "mode_parity__deep_freeze_recursion.wat",
        },
        Case {
            name: "mode_parity__good.wat",
        },
    ];
    let names: Vec<&str> = cases.iter().map(|c| c.name).collect();
    assert_eq!(
        names,
        [
            "mode_parity__empty.wat",
            "mode_parity__deep_freeze_recursion.wat",
            "mode_parity__good.wat"
        ],
        "an arm's fixture was dropped or renamed — the gate is not covering that arm"
    );
    for c in &cases {
        let p = fixture(c.name);
        assert!(p.is_file(), "missing fixture {}", p.display());
        eprintln!("mode-parity case: {}", c.name);
    }
}

/// Two drives to fire and two to refuse before the arms. Shape from
/// `probe_vig_value_hash_collision` calibration.
#[test]
fn mode_parity_calibration() {
    let good = fixture("mode_parity__good.wat");
    let empty = fixture("mode_parity__empty.wat");
    let bad = fixture("wat_cli__check_bad.wat");
    assert_eq!(
        drive(&["--check"], &good),
        Outcome::Accepted,
        "FIRE 1: --check accepts a well-formed program"
    );
    assert_eq!(
        drive(&[], &good),
        Outcome::Accepted,
        "FIRE 2: run accepts a well-formed program"
    );
    assert_eq!(
        drive(&[], &empty),
        Outcome::Rejected,
        "REFUSE 1: run rejects a program with no :user::main"
    );
    assert_eq!(
        drive(&["--check"], &bad),
        Outcome::Rejected,
        "REFUSE 2: --check rejects a type-incorrect program"
    );
}

/// SOUNDNESS arm. PINS the documented mode difference — never a claimed violation
/// (BRIEF-7m-ADDENDUM-388, finding 40). `mode_parity__empty.wat` has no `:user::main`, so
/// `--check` (a unit checker) Accepts it and the run path (needs an entry point) Rejects it:
/// `check=Accepted run=Rejected has_main=false`. `soundness_holds` must still return true here —
/// that is exactly the excluded reason the invariant names, proved against a real fixture rather
/// than only the mutation tests' hardcoded `Outcome`s.
#[test]
fn mode_parity_empty() {
    let path = fixture("mode_parity__empty.wat");
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    eprintln!("empty: --check={check:?} run={run:?}");
    assert_eq!(
        check,
        Outcome::Accepted,
        "--check is a unit checker: no :user::main is not a check failure; got {check:?}"
    );
    assert_eq!(
        run,
        Outcome::Rejected,
        "the run path needs an entry point and must still reject; got {run:?}"
    );
    assert!(
        soundness_holds(check, run, false),
        "the documented mode difference (missing entry point) must satisfy SOUNDNESS via its \
         excluded reason (check={check:?} run={run:?})"
    );
}

/// LIVENESS arm. Implication: if run Accepts, `--check` must not die by
/// signal. RED at #387 (SIGABRT 134 on 1000-deep freeze-time recursion); the
/// `RLIMIT_STACK` hoist at #388 (landed verbatim, not in dispute) cures it.
#[test]
fn mode_parity_deep_freeze_recursion() {
    let path = fixture("mode_parity__deep_freeze_recursion.wat");
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    eprintln!("deep: --check={check:?} run={run:?}");
    assert!(
        liveness_holds(check, run),
        "LIVENESS: run terminated normally but --check died by signal (check={check:?} run={run:?})"
    );
}

/// CONTROL. Both modes Accept. If this row is red the gate does not discriminate.
#[test]
fn mode_parity_good() {
    let path = fixture("mode_parity__good.wat");
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    assert_eq!(
        check,
        Outcome::Accepted,
        "good --check must Accept; got {check:?}"
    );
    assert_eq!(run, Outcome::Accepted, "good run must Accept; got {run:?}");
    assert!(
        soundness_holds(check, run, true),
        "SOUNDNESS on control (has_main=true — a declared, well-formed main): --check={check:?} run={run:?}"
    );
    assert!(
        !matches!(check, Outcome::DiedBySignal(_)),
        "LIVENESS on control: --check died by signal {check:?}"
    );
}

/// PROVES THE KEPT HALF (BRIEF-7m-ADDENDUM-388, finding 40): a DECLARED but malformed
/// `:user::main` must still fail `--check`, exactly as grok's original #388 motive stated —
/// narrowing the entry-point check to "declared" never weakens it for a program that HAS one.
/// Uses the pre-existing `wat_cli__wrong_arg_type_main.wat`
/// (`tests/cli/wat_cli.rs::wrong_arg_type_user_main_rejected`): a non-canonical return type on a
/// DECLARED `:user::main` fires a type-check error inside `startup_from_source` itself, before
/// the narrowed `check_only` branch's `Ok(world)` arm is ever reached — so this was true before
/// AND after #388's narrowing, and this test names it explicitly rather than leaving it implicit.
#[test]
fn mode_parity_malformed_main() {
    let path = fixture("wat_cli__wrong_arg_type_main.wat");
    assert!(path.is_file(), "missing fixture {}", path.display());
    let check = drive(&["--check"], &path);
    let run = drive(&[], &path);
    eprintln!("malformed main: --check={check:?} run={run:?}");
    assert_eq!(
        check,
        Outcome::Rejected,
        "a DECLARED but malformed :user::main must still fail --check; got {check:?}"
    );
    assert_eq!(
        run,
        Outcome::Rejected,
        "the run path must also reject a malformed main; got {run:?}"
    );
}

/// Mutation: this tree's ACTUAL SOUNDNESS cure — `--check` Accepts a no-main file
/// (`has_main=false`), satisfying SOUNDNESS via the excluded missing-entry-point reason — greens
/// that arm only. The LIVENESS defect (signal death + run Accept) stays red. (Updated at #388,
/// BRIEF-7m-ADDENDUM-388: grok's original stub assumed the OPPOSITE direction, "--check Rejects
/// the empty file"; the narrowed cure instead makes `--check` Accept it, which is the real,
/// landed shape.)
#[test]
fn mode_parity_soundness_cure_greens_only_that_arm() {
    assert!(
        soundness_holds(Outcome::Accepted, Outcome::Rejected, false),
        "the narrowed cure (--check Accepts a no-main file) must satisfy SOUNDNESS via the \
         excluded missing-entry-point reason"
    );
    assert!(
        !liveness_holds(Outcome::DiedBySignal(6), Outcome::Accepted),
        "SOUNDNESS cure must not green the LIVENESS defect"
    );
}

/// Mutation: a stub of the LIVENESS cure (deep `--check` Accepts) greens
/// that arm only. A SOUNDNESS defect where the run path rejects a DECLARED main for a reason
/// `--check` should have caught (`has_main=true`) stays red — the LIVENESS cure must not paper
/// over a genuine SOUNDNESS violation.
#[test]
fn mode_parity_liveness_cure_greens_only_that_arm() {
    assert!(
        liveness_holds(Outcome::Accepted, Outcome::Accepted),
        "cured deep (--check Accepts) must satisfy LIVENESS"
    );
    assert!(
        !soundness_holds(Outcome::Accepted, Outcome::Rejected, true),
        "LIVENESS cure must not green a genuine SOUNDNESS defect (has_main=true — a declared \
         main the run path rejected for a reason --check could have seen)"
    );
}
