//! Test home for `src/collection/` — behavior-named tests (arc lineage in git, not filenames).
//! Module list generated by build.rs into OUT_DIR (drop a .rs here → auto-compiled, no manual step).
//! Run: cargo test --release -p wat --test collection
include!(concat!(env!("OUT_DIR"), "/collection_mods.rs"));
