//! build.rs — auto-generate the module list for every grouped integration-test
//! binary, so a test file can NEVER be silently forgotten.
//!
//! # Why this exists (the failure class it annihilates)
//!
//! Grouped integration tests live under `tests/<group>/` with a single
//! `[[test]] path = "tests/<group>/mod.rs"` Cargo entry; the sibling `*.rs`
//! files are brought in via `mod` declarations. Previously that list was
//! hand-maintained by a bash script (`gen-test-mods.sh`) you had to REMEMBER
//! to run; a `--check` gate caught drift only at green-gate time, leaving a
//! dev-loop window where a freshly-added test was simply not compiled.
//!
//! This build script removes the window by construction. Cargo runs `build.rs`
//! on every build/test, so the list is ALWAYS current — there is no committed
//! mod-list to drift, no script to forget, no gate to maintain. Drop a `.rs`
//! into a group dir and it is compiled + run on the next `cargo test`. The
//! mod-list is generated into `OUT_DIR` (never the source tree — a build script
//! that rewrites tracked files dirties git and can need two builds to settle);
//! each group's committed `mod.rs` is a thin `include!` stub.
//!
//! # Later (the wat-as-management track)
//!
//! The dir-listing + list computation will migrate to wat once wat has fs
//! syscalls (`readdir`) — run as a separately-distributed, prebuilt stage0 wat
//! binary used to bootstrap the build (the rustc pattern), NOT called from
//! within this crate's own build (which is circular: the binary is what's being
//! built). Until then this stays pure Rust — the always-runs guarantee.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let tests_dir = Path::new(&manifest).join("tests");

    // Re-run if this script changes.
    println!("cargo:rerun-if-changed=build.rs");

    let entries = match fs::read_dir(&tests_dir) {
        Ok(e) => e,
        Err(_) => return, // no tests/ dir → nothing to generate
    };

    for entry in entries.flatten() {
        let dir = entry.path();
        if !dir.is_dir() {
            continue;
        }
        // A group is any tests/<group>/ that opts in by having a mod.rs.
        if !dir.join("mod.rs").exists() {
            continue;
        }
        let group = match dir.file_name().and_then(|n| n.to_str()) {
            Some(g) => g.to_string(),
            None => continue,
        };

        // Re-run when files are added/removed in this group dir (Linux tracks
        // the dir's mtime, so a new/deleted sibling .rs re-triggers generation).
        println!("cargo:rerun-if-changed=tests/{group}");

        // Every sibling *.rs except mod.rs, sorted for a stable, diffable list.
        let mut stems: Vec<String> = fs::read_dir(&dir)
            .expect("read group dir")
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().map(|x| x == "rs").unwrap_or(false))
            .filter(|p| p.file_name().map(|n| n != "mod.rs").unwrap_or(false))
            .filter_map(|p| p.file_stem().and_then(|s| s.to_str()).map(String::from))
            .collect();
        stems.sort();

        let mut generated = String::new();
        generated.push_str(&format!(
            "// @generated by build.rs — do not edit. Module list for the `{group}`\n\
             // integration-test group, derived from tests/{group}/*.rs at build time.\n"
        ));
        for stem in &stems {
            let abs = dir.join(format!("{stem}.rs"));
            let abs = abs.to_str().expect("utf-8 path");
            // Absolute #[path] is robust regardless of the include! site.
            // #[allow(non_snake_case)]: some arc-numbered test files carry
            // capitals (e.g. probe_arc237_sC2ab_*); the names are intentional.
            generated.push_str(&format!(
                "#[allow(non_snake_case)]\n#[path = {abs:?}]\nmod {stem};\n"
            ));
        }

        let dest = Path::new(&out_dir).join(format!("{group}_mods.rs"));
        fs::write(&dest, generated).expect("write generated mod list");
    }

    // Arc 170 step 4 — a spawned runtime EXECS the `wat` binary. A process that
    // never entered wat's CLI entry (a cargo test harness, whose `main` belongs
    // to libtest) cannot serve as one, so it needs to know where the real
    // binary is. OUT_DIR is `target/<profile>/build/<pkg>-<hash>/out`; three
    // parents up is `target/<profile>/`, where cargo puts the bin targets.
    if let Ok(out_dir) = std::env::var("OUT_DIR") {
        let profile_dir = std::path::Path::new(&out_dir)
            .ancestors()
            .nth(3)
            .map(std::path::Path::to_path_buf);
        if let Some(dir) = profile_dir {
            println!(
                "cargo:rustc-env=WAT_RUNTIME_BIN_DEFAULT={}",
                dir.join("wat").display()
            );
        }
    }

    generate_every_probe_runs(&manifest, &out_dir);
}

/// Stone 255.75 ("every probe runs" — ruling E3): ONE generated `#[test]` per
/// `wat-scripts/probes/**/*.wat` (never `.wat.bad`), so a red names the exact
/// probe and nextest runs them in parallel. Included by
/// `tests/process/every_probe_runs.rs` (a thin `include!`), which rides the
/// `tests/process/` group's own build.rs mod-registration above. A probe
/// dropped anywhere under `wat-scripts/probes/` is picked up with NO edit
/// here: `rerun-if-changed` is emitted for the root and every subdirectory
/// found, so adding/removing a `.wat` file (which changes its parent dir's
/// mtime) re-triggers this generation on the next build.
fn generate_every_probe_runs(manifest: &str, out_dir: &str) {
    let probes_root = Path::new(manifest).join("wat-scripts/probes");
    println!("cargo:rerun-if-changed={}", probes_root.display());

    let mut wat_files: Vec<String> = Vec::new();
    collect_wat_files(Path::new(manifest), &probes_root, &mut wat_files);
    wat_files.sort();

    let mut generated = String::from(
        "// @generated by build.rs — do not edit. Stone 255.75 (\"every probe\n\
         // runs\", ruling E3): one #[test] per wat-scripts/probes/**/*.wat\n\
         // (excluding .wat.bad), run with the release binary, stdin /dev/null,\n\
         // a 10s timeout, requiring exit 0.\n\
         use std::path::Path;\n\
         use std::process::{Command, Stdio};\n\
         use std::sync::atomic::{AtomicBool, Ordering};\n\
         use std::sync::Arc;\n\
         use std::time::Duration;\n\n\
         fn run_probe(rel: &str) {\n\
         \x20   let manifest = Path::new(env!(\"CARGO_MANIFEST_DIR\"));\n\
         \x20   let bin = env!(\"CARGO_BIN_EXE_wat\");\n\
         \x20   let child = Command::new(bin)\n\
         \x20       .arg(manifest.join(rel))\n\
         \x20       .current_dir(manifest)\n\
         \x20       .stdin(Stdio::null())\n\
         \x20       .stdout(Stdio::piped())\n\
         \x20       .stderr(Stdio::piped())\n\
         \x20       .spawn()\n\
         \x20       .unwrap_or_else(|e| panic!(\"spawn {bin} {rel}: {e}\"));\n\
         \x20   let pid = child.id();\n\
         \x20   let done = Arc::new(AtomicBool::new(false));\n\
         \x20   let done2 = Arc::clone(&done);\n\
         \x20   let _watchdog = std::thread::spawn(move || {\n\
         \x20       std::thread::sleep(Duration::from_secs(10));\n\
         \x20       if !done2.load(Ordering::SeqCst) {\n\
         \x20           let _ = Command::new(\"kill\").arg(\"-9\").arg(pid.to_string()).status();\n\
         \x20       }\n\
         \x20   });\n\
         \x20   let out = child\n\
         \x20       .wait_with_output()\n\
         \x20       .unwrap_or_else(|e| panic!(\"wait {bin} {rel}: {e}\"));\n\
         \x20   done.store(true, Ordering::SeqCst);\n\
         \x20   // Deliberately NOT joined: the watchdog sleeps up to 10s and would hold a\n\
         \x20   // fast-exiting probe's test to the full timeout. It is a no-op once `done`\n\
         \x20   // is set, and nextest runs each test in its own process, so a detached\n\
         \x20   // sleeper is reaped with the process at the end of this test either way.\n\
         \x20   let stdout = String::from_utf8_lossy(&out.stdout).into_owned();\n\
         \x20   let stderr = String::from_utf8_lossy(&out.stderr).into_owned();\n\
         \x20   assert_eq!(\n\
         \x20       out.status.code(),\n\
         \x20       Some(0),\n\
         \x20       \"{rel} must run clean (exit 0) — ruling E3, \\\"the floor runs every probe \\\n\
         \x20        and requires exit 0\\\"; stdout:\\n{stdout}\\nstderr:\\n{stderr}\"\n\
         \x20   );\n\
         }\n\n",
    );

    for rel in &wat_files {
        let fn_name = probe_fn_name(rel);
        generated.push_str(&format!(
            "#[allow(non_snake_case)]\n#[test]\nfn {fn_name}() {{\n    run_probe({rel:?});\n}}\n\n"
        ));
    }

    let dest = Path::new(out_dir).join("every_probe_runs.rs");
    fs::write(&dest, generated).expect("write generated every-probe-runs test list");
}

/// Recurse `dir`, collecting every `*.wat` (never `*.wat.bad`) found under
/// `root`, as a `wat-scripts/probes/...`-relative path string. Emits
/// `rerun-if-changed` for every subdirectory visited, so a file added/removed
/// anywhere in the tree (which touches its immediate parent's mtime)
/// re-triggers generation.
fn collect_wat_files(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            collect_wat_files(root, &path, out);
            continue;
        }
        let is_wat = path.extension().map(|x| x == "wat").unwrap_or(false);
        if !is_wat {
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .expect("probe path under manifest root")
            .to_str()
            .expect("utf-8 probe path")
            .replace('\\', "/");
        out.push(rel);
    }
}

/// `wat-scripts/probes/arc-170/probe-bracket-cause.wat` → a valid, unique
/// Rust test fn identifier.
fn probe_fn_name(rel: &str) -> String {
    let stem = rel.trim_end_matches(".wat");
    let cleaned: String = stem
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    format!("probe_{cleaned}")
}
