//! build.rs — auto-generate the module list for every grouped integration-test
//! binary, so a test file can NEVER be silently forgotten.
//!
//! # Why this exists (the failure class it annihilates)
//!
//! Grouped integration tests live under `tests/<group>/` with a single
//! `[[test]] path = "tests/<group>/mod.rs"` Cargo entry; the sibling `*.rs`
//! files are brought in via `mod` declarations. Previously that list was
//! hand-maintained by a bash script (`gen-test-mods.sh`) you had to REMEMBER
//! to run; a `--check` gate caught drift only at green-gate time, leaving a
//! dev-loop window where a freshly-added test was simply not compiled.
//!
//! This build script removes the window by construction. Cargo runs `build.rs`
//! on every build/test, so the list is ALWAYS current — there is no committed
//! mod-list to drift, no script to forget, no gate to maintain. Drop a `.rs`
//! into a group dir and it is compiled + run on the next `cargo test`. The
//! mod-list is generated into `OUT_DIR` (never the source tree — a build script
//! that rewrites tracked files dirties git and can need two builds to settle);
//! each group's committed `mod.rs` is a thin `include!` stub.
//!
//! # Later (the wat-as-management track)
//!
//! The dir-listing + list computation will migrate to wat once wat has fs
//! syscalls (`readdir`) — run as a separately-distributed, prebuilt stage0 wat
//! binary used to bootstrap the build (the rustc pattern), NOT called from
//! within this crate's own build (which is circular: the binary is what's being
//! built). Until then this stays pure Rust — the always-runs guarantee.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let tests_dir = Path::new(&manifest).join("tests");

    boot_cache_fingerprint(&manifest);

    // Re-run if this script changes.
    println!("cargo:rerun-if-changed=build.rs");

    let entries = match fs::read_dir(&tests_dir) {
        Ok(e) => e,
        Err(_) => return, // no tests/ dir → nothing to generate
    };

    for entry in entries.flatten() {
        let dir = entry.path();
        if !dir.is_dir() {
            continue;
        }
        // A group is any tests/<group>/ that opts in by having a mod.rs.
        if !dir.join("mod.rs").exists() {
            continue;
        }
        let group = match dir.file_name().and_then(|n| n.to_str()) {
            Some(g) => g.to_string(),
            None => continue,
        };

        // Re-run when files are added/removed in this group dir (Linux tracks
        // the dir's mtime, so a new/deleted sibling .rs re-triggers generation).
        println!("cargo:rerun-if-changed=tests/{group}");

        // Every sibling *.rs except mod.rs, sorted for a stable, diffable list.
        let mut stems: Vec<String> = fs::read_dir(&dir)
            .expect("read group dir")
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().map(|x| x == "rs").unwrap_or(false))
            .filter(|p| p.file_name().map(|n| n != "mod.rs").unwrap_or(false))
            .filter_map(|p| p.file_stem().and_then(|s| s.to_str()).map(String::from))
            .collect();
        stems.sort();

        let mut generated = String::new();
        generated.push_str(&format!(
            "// @generated by build.rs — do not edit. Module list for the `{group}`\n\
             // integration-test group, derived from tests/{group}/*.rs at build time.\n"
        ));
        for stem in &stems {
            let abs = dir.join(format!("{stem}.rs"));
            let abs = abs.to_str().expect("utf-8 path");
            // Absolute #[path] is robust regardless of the include! site.
            // #[allow(non_snake_case)]: some arc-numbered test files carry
            // capitals (e.g. probe_arc237_sC2ab_*); the names are intentional.
            generated.push_str(&format!(
                "#[allow(non_snake_case)]\n#[path = {abs:?}]\nmod {stem};\n"
            ));
        }

        let dest = Path::new(&out_dir).join(format!("{group}_mods.rs"));
        fs::write(&dest, generated).expect("write generated mod list");
    }

    // Arc 170 step 4 — a spawned runtime EXECS the `wat` binary. A process that
    // never entered wat's CLI entry (a cargo test harness, whose `main` belongs
    // to libtest) cannot serve as one, so it needs to know where the real
    // binary is. OUT_DIR is `target/<profile>/build/<pkg>-<hash>/out`; three
    // parents up is `target/<profile>/`, where cargo puts the bin targets.
    if let Ok(out_dir) = std::env::var("OUT_DIR") {
        let profile_dir = std::path::Path::new(&out_dir)
            .ancestors()
            .nth(3)
            .map(std::path::Path::to_path_buf);
        if let Some(dir) = profile_dir {
            println!(
                "cargo:rustc-env=WAT_RUNTIME_BIN_DEFAULT={}",
                dir.join("wat").display()
            );
        }
    }
}

// ─── Boot cache fingerprint ──────────────────────────────────────────────────
//
// Excursus 001 `the-boot-cache-elides-what-it-already-knows` (Tier A). The boot
// cache stores the *derived* stdlib world (expanded macros + registered types +
// registered functions). Two INDEPENDENT things can invalidate it:
//
//   1. the stdlib SOURCE changed  (`wat/**/*.wat` — baked via `include_str!`)
//   2. the RUST that derives from it changed (the expander, the registrars, the
//      AST, the cache format itself)
//
// (2) is the one a source-only hash misses, and missing it is the dangerous
// direction: a stale cache that is USED. So the fingerprint below covers every
// input that can change either — the wat corpus, this crate's `src/`, every
// workspace crate's `src/`, `Cargo.lock`, and this script — and a
// `cargo:rerun-if-changed` line is emitted per FILE (a directory-level line only
// catches add/delete on Linux, never an edit to an existing file).
//
// Hash: two FNV-1a-64 passes with different offset bases, concatenated to 128
// bits. Hand-rolled because a build script may not use the crate's own
// dependencies and this needs no crate of its own — the same reasoning that kept
// the payload format dependency-free.
fn boot_cache_fingerprint(manifest: &str) {
    const ROOTS: &[&str] = &["wat", "src", "crates", "Cargo.lock", "Cargo.toml", "build.rs"];
    let root = Path::new(manifest);
    let mut files: Vec<std::path::PathBuf> = Vec::new();
    for r in ROOTS {
        collect(&root.join(r), &mut files);
    }
    files.sort();

    // Two independent 64-bit mixes (FNV-1a, and a rotate+odd-multiply) → 128 bits.
    let (mut a, mut b) = (0xcbf2_9ce4_8422_2325u64, 0x9ae1_6a3b_2f90_404fu64);
    let mut feed = |bytes: &[u8]| {
        for &x in bytes {
            a = (a ^ u64::from(x)).wrapping_mul(0x0000_0100_0000_01b3);
            b = (b ^ u64::from(x)).rotate_left(27).wrapping_mul(0x9E37_79B9_7F4A_7C15);
        }
    };
    for f in &files {
        let rel = f.strip_prefix(root).unwrap_or(f);
        println!("cargo:rerun-if-changed={}", f.display());
        feed(rel.to_string_lossy().as_bytes());
        feed(b"\0");
        match fs::read(f) {
            Ok(bytes) => feed(&bytes),
            Err(_) => feed(b"<unreadable>"),
        }
        feed(b"\0");
    }
    println!("cargo:rustc-env=WAT_BUILD_FINGERPRINT={a:016x}{b:016x}");
}

/// Every regular file under `p` (recursively), or `p` itself when it is a file.
/// `target/` and dot-directories are skipped — neither feeds the derivation.
fn collect(p: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(md) = fs::metadata(p) else { return };
    if md.is_file() {
        out.push(p.to_path_buf());
        return;
    }
    if !md.is_dir() {
        return;
    }
    let Ok(rd) = fs::read_dir(p) else { return };
    for e in rd.flatten() {
        let child = e.path();
        let name = child.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default();
        if name.starts_with('.') || name == "target" {
            continue;
        }
        collect(&child, out);
    }
}
