;; wat-scripts/scratch-pad/255-stone-h-1b-atom-wrong-arity.wat — arc 255 Stone H-1b.
;; row 2's WRONG-ARITY half: call every one of the 60 atom.rs verbs with one arg
;; short of its real arity, catch the RuntimeError via (:wat::eval-ast! (quote ...)),
;; and print kind+message so before/after can be diffed byte-for-byte. The 8 verbs
;; STOP-1/STOP-2 left `args: &[WatAST]` (from-holon, literal, and the six
;; eval-*-coincident? family) are included too, as a no-op regression check — their
;; hand-rolled checks are untouched by this stone. Mirrors
;; 255-stone-h-1a-holon-wrong-arity.wat's shape.

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::do
    (:wat::kernel::println "── :wat::holon::from-holon (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::from-holon)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Atom (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Atom)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::to-holon (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::to-holon)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::leaf (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::leaf)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::from-wat (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::from-wat)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::to-wat (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::to-wat)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::literal (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::literal)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::to-record (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::to-record 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Map (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Map)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Set (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Set)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Vector (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Vector)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::List (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::List)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Tuple (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Tuple)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bind (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bind 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bundle (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bundle)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Permute (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Permute 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Thermometer (wrong-arity, 2 of 3) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Thermometer 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Blend (wrong-arity, 3 of 4) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Blend 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::extract-classifier (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::extract-classifier)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bind/left (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bind/left)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bind/right (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bind/right)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bundle/children (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bundle/children)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bundle/first (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bundle/first)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Map? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Map?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Set? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Set?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Vector? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Vector?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-List? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-List?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Tuple? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Tuple?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Symbol? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Symbol?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Keyword? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Keyword?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Tag? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Tag?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Nil? (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Nil?)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is? (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is? 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::template (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::template)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::slots (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::slots)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::ranges (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::ranges)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::matches? (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::matches? 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::therm-form (wrong-arity, 2 of 3) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::therm-form 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::presence-floor (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::presence-floor)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::coincident-floor (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::coincident-floor)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::cosine (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::cosine 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::presence? (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::presence? 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::coincident? (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::coincident? 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::coincident-explain (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::coincident-explain 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::eval-coincident? (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::eval-coincident? 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::eval-edn-coincident? (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::eval-edn-coincident? 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::eval-digest-coincident? (wrong-arity, 7 of 8) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::eval-digest-coincident? 1 1 1 1 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::eval-digest-string-coincident? (wrong-arity, 7 of 8) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::eval-digest-string-coincident? 1 1 1 1 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::eval-signed-coincident? (wrong-arity, 11 of 12) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::eval-signed-coincident? 1 1 1 1 1 1 1 1 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::eval-signed-string-coincident? (wrong-arity, 11 of 12) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::eval-signed-string-coincident? 1 1 1 1 1 1 1 1 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::dot (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::dot 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::simhash (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::simhash)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::encode (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::encode)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-bytes (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-bytes)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::bytes-vector (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::bytes-vector)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-bind (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-bind 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-bundle (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-bundle)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-blend (wrong-arity, 3 of 4) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-blend 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-permute (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-permute 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::statement-length (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::statement-length)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    nil))
