;; wat-scripts/scratch-pad/255-stone-h-1a-holon-wrong-arity.wat — arc 255 Stone H-1a.
;; row 1's WRONG-ARITY half: call every one of the 35 holon verbs with one arg
;; short of its declared arity, catch the RuntimeError via (:wat::eval-ast! (quote ...)),
;; and print kind+message so before/after can be diffed byte-for-byte. Scratch, per
;; holon/CLAUDE.md's .wat scratch convention.

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::do
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/new (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/new 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/dim (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/dim)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/k (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/k)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/n (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/n)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/threshold (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/threshold)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/eigenvalues (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/eigenvalues)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/update (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/update 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/residual (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/residual 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/project (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/project 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::OnlineSubspace/reconstruct (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::OnlineSubspace/reconstruct 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Engram/name (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Engram/name)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Engram/eigenvalue-signature (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Engram/eigenvalue-signature)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Engram/n (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Engram/n)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Engram/residual (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Engram/residual 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::EngramLibrary/new (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::EngramLibrary/new)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::EngramLibrary/add (wrong-arity, 2 of 3) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::EngramLibrary/add 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::EngramLibrary/match-vec (wrong-arity, 3 of 4) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::EngramLibrary/match-vec 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::EngramLibrary/len (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::EngramLibrary/len)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::EngramLibrary/contains (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::EngramLibrary/contains 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::EngramLibrary/names (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::EngramLibrary/names)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/new-discrete (wrong-arity, 3 of 4) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/new-discrete 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/new-continuous (wrong-arity, 4 of 5) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/new-continuous 1 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/observe (wrong-arity, 3 of 4) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/observe 1 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/predict (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/predict 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/resolve (wrong-arity, 2 of 3) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/resolve 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/curve (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/curve)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/labels (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/labels)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Reckoner/dims (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Reckoner/dims)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/make (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/make)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/put (wrong-arity, 2 of 3) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/put 1 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/get (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/get 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/find (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/find 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/remove (wrong-arity, 1 of 2) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/remove 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/len (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/len)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Hologram/capacity (wrong-arity, 0 of 1) ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Hologram/capacity)))
      ((:wat::core::Ok _) (:wat::kernel::println "UNEXPECTED: ok"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    nil))
