;; wat-scripts/scratch-pad/255-stone-h-1b-atom-success-calls.wat — arc 255 Stone H-1b.
;; row 2's SUCCESS half: exercise every one of the 54 runnable-`@example` atom.rs
;; verbs (the six `eval-*-coincident?` verbs are `@example-norun` and are not run
;; here) at its real arity via the verb's own doc `@example` expression, catching
;; via `(:wat::eval-ast! (quote ...))` so before/after can be diffed byte-for-byte.
;; The Ok arm prints a fixed "OK" marker rather than `pprintln`-ing the raw result —
;; several examples (Atom/Bind/Map/... ) return bare algebra HolonASTs, which
;; DESIGN-STONE-294.j forbids crossing the EDN wire (pprintln panics on them by
;; design, identically before and after this stone — confirmed, not a regression).
;; Mirrors 255-stone-h-1a-holon-success-calls.wat's shape.

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::do
    (:wat::kernel::println "── :wat::holon::from-holon ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::from-holon (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Atom ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Atom (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::to-holon ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::to-holon "role")))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::leaf ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::leaf 5)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::from-wat ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::from-wat (:wat::core::quote (:wat::i64::+ 1 2)))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::to-wat ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::to-wat (:wat::holon::from-wat (:wat::core::quote x)))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::literal ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::literal (f x))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::to-record ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::core::do (:wat::core::defstruct :probe::Pt [x <- :wat::core::i64]) (:wat::core::defsurface :probe::Planar :nature :wat::core::Struct :features [x <- :wat::core::i64]) (:wat::holon::to-record (:probe::Pt :x 3) :probe::Planar))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Map ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Map (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::Bind (:wat::holon::leaf "k") (:wat::holon::leaf "v"))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Set ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Set (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Vector ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Vector (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::List ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::List (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Tuple ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Tuple (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bind ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bundle ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bundle (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Permute ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Permute (:wat::holon::leaf "role") 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Thermometer ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Thermometer 5.0 0.0 10.0)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Blend ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Blend (:wat::holon::leaf "role") (:wat::holon::leaf "filler") 0.7 0.3)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::extract-classifier ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::extract-classifier (:wat::holon::Vector (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role"))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bind/left ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bind/left (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bind/right ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::Bind/right (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bundle/children ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::core::match (:wat::holon::Bundle (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role") (:wat::holon::leaf "filler"))) ((:wat::core::Ok h) (:wat::holon::Bundle/children h)) (_ (:wat::holon::Bundle/children (:wat::holon::leaf "unreachable"))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::Bundle/first ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::core::match (:wat::holon::Bundle (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role") (:wat::holon::leaf "filler"))) ((:wat::core::Ok h) (:wat::holon::Bundle/first h)) (_ (:wat::holon::Bundle/first (:wat::holon::leaf "unreachable"))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Map? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Map? (:wat::holon::Map (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::Bind (:wat::holon::leaf "k") (:wat::holon::leaf "v")))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Set? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Set? (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Vector? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Vector? (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-List? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-List? (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Tuple? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Tuple? (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Symbol? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Symbol? (:wat::holon::from-wat (:wat::core::quote x)))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Keyword? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Keyword? (:wat::holon::from-wat (:wat::core::quote :k)))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Tag? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Tag? (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is-Nil? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is-Nil? (:wat::holon::to-holon nil))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::is? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::is? (:wat::holon::leaf "role") "Vector")))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::template ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::template (:wat::holon::Thermometer 5.0 0.0 10.0))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::slots ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::slots (:wat::holon::Thermometer 5.0 0.0 10.0))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::ranges ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::ranges (:wat::holon::Thermometer 5.0 0.0 10.0))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::term::matches? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::term::matches? (:wat::holon::Thermometer 5.0 0.0 10.0) (:wat::holon::Thermometer 5.0 0.0 10.0))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::therm-form ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::therm-form 0.0 10.0 5.0)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::presence-floor ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::presence-floor 4096)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::coincident-floor ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::coincident-floor 4096)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::cosine ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::cosine (:wat::holon::leaf "role") (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::presence? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::presence? (:wat::holon::leaf "role") (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::coincident? ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::coincident? (:wat::holon::leaf "role") (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::coincident-explain ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::coincident-explain (:wat::holon::leaf "role") (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::dot ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::dot (:wat::holon::leaf "role") (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::simhash ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::simhash (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::encode ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::encode (:wat::holon::leaf "role"))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-bytes ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-bytes (:wat::holon::encode (:wat::holon::leaf "role")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::bytes-vector ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::bytes-vector (:wat::holon::vector-bytes (:wat::holon::encode (:wat::holon::leaf "role"))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-bind ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-bind (:wat::holon::encode (:wat::holon::leaf "role")) (:wat::holon::encode (:wat::holon::leaf "filler")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-bundle ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-bundle (:wat::core::Vector :- [:wat::holon::Vector] (:wat::holon::encode (:wat::holon::leaf "role")) (:wat::holon::encode (:wat::holon::leaf "filler"))))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-blend ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-blend (:wat::holon::encode (:wat::holon::leaf "role")) (:wat::holon::encode (:wat::holon::leaf "filler")) 0.7 0.3)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::vector-permute ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::vector-permute (:wat::holon::encode (:wat::holon::leaf "role")) 1)))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    (:wat::kernel::println "── :wat::holon::statement-length ──")
    (:wat::core::match (:wat::eval-ast! (:wat::core::quote (:wat::holon::statement-length (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))))
      ((:wat::core::Ok _) (:wat::kernel::println "OK"))
      ((:wat::core::Err e)
        (:wat::kernel::println (:wat::string::concat "ERR kind=" (:wat::core::EvalError/kind e)
                                  " message=" (:wat::core::EvalError/message e)))))
    nil))
