;; RELAND 8 STOP-4: type-of stdlib enums the campaign could have corrupted.
;; A FQDN in a variant :name is the Option-None class of corruption.

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::kernel::println "=== Option ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::core::Option))
  (:wat::kernel::println "=== Result ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::core::Result))
  (:wat::kernel::println "=== RecvOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::RecvOutcome))
  (:wat::kernel::println "=== SendOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::SendOutcome))
  (:wat::kernel::println "=== TrySendOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::TrySendOutcome))
  (:wat::kernel::println "=== CloseOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::CloseOutcome))
  (:wat::kernel::println "=== Signal ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::Signal))
  (:wat::kernel::println "=== SignalOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::SignalOutcome))
  (:wat::kernel::println "=== AcceptOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::AcceptOutcome))
  (:wat::kernel::println "=== ConnectOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::ConnectOutcome))
  (:wat::kernel::println "=== RunResult ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::RunResult))
  (:wat::kernel::println "=== ReadFrameOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::ReadFrameOutcome))
  (:wat::kernel::println "=== ReadlnOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::ReadlnOutcome))
  (:wat::kernel::println "=== LociDiedError ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::kernel::LociDiedError))
  (:wat::kernel::println "=== BreakKind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::fmt::BreakKind))
  (:wat::kernel::println "=== NodeKind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::grep::NodeKind))
  (:wat::kernel::println "=== WalkStep ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::eval::WalkStep))
  (:wat::kernel::println "=== StepResult ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::eval::StepResult))
  (:wat::kernel::println "=== FormOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::eval::FormOutcome))
  (:wat::kernel::println "=== Numeric ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::telemetry::Numeric))
  (:wat::kernel::println "=== Unit ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::telemetry::Unit))
  (:wat::kernel::println "=== Level ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::telemetry::Level))
  (:wat::kernel::println "=== telemetry Kind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::telemetry::Kind))
  (:wat::kernel::println "=== TypeKind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::TypeKind))
  (:wat::kernel::println "=== TypeNature ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::TypeNature))
  (:wat::kernel::println "=== TypePurity ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::TypePurity))
  (:wat::kernel::println "=== TypeSurfaceMember ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::TypeSurfaceMember))
  (:wat::kernel::println "=== TypeBody ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::TypeBody))
  (:wat::kernel::println "=== runtime Kind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::Kind))
  (:wat::kernel::println "=== DefinedIn ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::DefinedIn))
  (:wat::kernel::println "=== Layer ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::Layer))
  (:wat::kernel::println "=== Purity ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::Purity))
  (:wat::kernel::println "=== Determinism ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::Determinism))
  (:wat::kernel::println "=== Category ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::Category))
  (:wat::kernel::println "=== Totality ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::Totality))
  (:wat::kernel::println "=== ExpandTime ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::runtime::ExpandTime))
  (:wat::kernel::println "=== ReadJsonOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::edn::ReadJsonOutcome))
  (:wat::kernel::println "=== ReadForeignOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::edn::ReadForeignOutcome))
  (:wat::kernel::println "=== Validation ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::edn::Validation))
  (:wat::kernel::println "=== sqlite Error ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::sqlite::Error))
  (:wat::kernel::println "=== Param ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::sqlite::Param))
  (:wat::kernel::println "=== Cell ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::sqlite::Cell))
  (:wat::kernel::println "=== NextOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::stream::NextOutcome))
  (:wat::kernel::println "=== PeerKind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::program::PeerKind))
  (:wat::kernel::println "=== service Outcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::service::Outcome))
  (:wat::kernel::println "=== Sieve ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::query::Sieve))
  (:wat::kernel::println "=== IOReader ReadFrameOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::io::IOReader::ReadFrameOutcome))
  (:wat::kernel::println "=== VectorDecodeOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::holon::VectorDecodeOutcome))
  (:wat::kernel::println "=== CombineOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::holon::CombineOutcome))
  (:wat::kernel::println "=== DegenerateSide ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::holon::DegenerateSide))
  (:wat::kernel::println "=== CosineOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::holon::CosineOutcome))
  (:wat::kernel::println "=== DotOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::holon::DotOutcome))
  (:wat::kernel::println "=== HologramFilterKind ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::cache::HologramFilterKind))
  (:wat::kernel::println "=== Axis ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::rete::Axis))
  (:wat::kernel::println "=== ServiceEvent ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::spawn::ServiceEvent))
  (:wat::kernel::println "=== PoolMsg ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::bracket::PoolMsg))
  (:wat::kernel::println "=== ReadOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::core::ReadOutcome))
  (:wat::kernel::println "=== ReadWithCommentsOutcome ===")
  (:wat::kernel::pprintln (:wat::runtime::type-of :wat::core::ReadWithCommentsOutcome))
  nil)
