;; Scratch probe — Stone HOME-8. Runs the EXACT expression each Pure+Deterministic
;; :wat::holon::* verb's doc @example will use (as both `expr` and `expected`,
;; since determinism guarantees the same call yields the same result), so every
;; example is verified to actually execute before it ships in the doc comment.
;; Not a permanent fixture.

(:wat::core::defstruct :probe::Pt [x <- :wat::core::i64])
(:wat::core::defsurface :probe::Planar :nature :wat::core::Struct
  :features [x <- :wat::core::i64])

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::let
    [v01 (:wat::holon::Atom (:wat::holon::leaf "role"))
     v02 (:wat::holon::to-holon "role")
     v03 (:wat::holon::from-holon (:wat::holon::leaf "role"))
     v04 (:wat::holon::leaf 5)
     v05 (:wat::holon::from-wat (:wat::core::quote (:wat::i64::+ 1 2)))
     v06 (:wat::holon::to-wat (:wat::holon::from-wat (:wat::core::quote x)))
     v07 (:wat::holon::literal (f x))
     v08 (:wat::holon::to-record (:probe::Pt :x 3) :probe::Planar)
     v09 (:wat::holon::Map (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::Bind (:wat::holon::leaf "k") (:wat::holon::leaf "v"))))
     v10 (:wat::holon::Set (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))
     v11 (:wat::holon::Vector (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))
     v12 (:wat::holon::List (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))
     v13 (:wat::holon::Tuple (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role")))
     v14 (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler"))
     v15 (:wat::holon::Bundle (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))
     v16 (:wat::holon::Permute (:wat::holon::leaf "role") 1)
     v17 (:wat::holon::Thermometer 5.0 0.0 10.0)
     v18 (:wat::holon::Blend (:wat::holon::leaf "role") (:wat::holon::leaf "filler") 0.7 0.3)
     v19 (:wat::holon::extract-classifier (:wat::holon::Vector (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role"))))
     v20 (:wat::holon::Bind/left (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))
     v21 (:wat::holon::Bind/right (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))
     v22 (:wat::holon::Bind/left (:wat::holon::leaf "role"))
     v23 (:wat::holon::is-Map? (:wat::holon::Map (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::Bind (:wat::holon::leaf "k") (:wat::holon::leaf "v")))))
     v24 (:wat::holon::is-Set? (:wat::holon::leaf "role"))
     v25 (:wat::holon::is-Vector? (:wat::holon::leaf "role"))
     v26 (:wat::holon::is-List? (:wat::holon::leaf "role"))
     v27 (:wat::holon::is-Tuple? (:wat::holon::leaf "role"))
     v28 (:wat::holon::is-Symbol? (:wat::holon::from-wat (:wat::core::quote x)))
     v29 (:wat::holon::is-Keyword? (:wat::holon::from-wat (:wat::core::quote :k)))
     v30 (:wat::holon::is-Tag? (:wat::holon::leaf "role"))
     v31 (:wat::holon::is-Nil? (:wat::holon::to-holon nil))
     v32 (:wat::holon::is? (:wat::holon::leaf "role") "Vector")
     v33 (:wat::holon::term::template (:wat::holon::Thermometer 5.0 0.0 10.0))
     v34 (:wat::holon::term::slots (:wat::holon::Thermometer 5.0 0.0 10.0))
     v35 (:wat::holon::term::ranges (:wat::holon::Thermometer 5.0 0.0 10.0))
     v36 (:wat::holon::term::matches? (:wat::holon::Thermometer 5.0 0.0 10.0) (:wat::holon::Thermometer 5.0 0.0 10.0))
     v37 (:wat::holon::therm-form 0.0 10.0 5.0)
     v38 (:wat::holon::presence-floor 4096)
     v39 (:wat::holon::coincident-floor 4096)
     v40 (:wat::holon::cosine (:wat::holon::leaf "role") (:wat::holon::leaf "role"))
     v41 (:wat::holon::presence? (:wat::holon::leaf "role") (:wat::holon::leaf "role"))
     v42 (:wat::holon::coincident? (:wat::holon::leaf "role") (:wat::holon::leaf "role"))
     v43 (:wat::holon::coincident-explain (:wat::holon::leaf "role") (:wat::holon::leaf "role"))
     v44 (:wat::holon::dot (:wat::holon::leaf "role") (:wat::holon::leaf "role"))
     v45 (:wat::holon::simhash (:wat::holon::leaf "role"))
     v46 (:wat::holon::encode (:wat::holon::leaf "role"))
     v47 (:wat::holon::vector-bytes (:wat::holon::encode (:wat::holon::leaf "role")))
     v48 (:wat::holon::bytes-vector (:wat::holon::vector-bytes (:wat::holon::encode (:wat::holon::leaf "role"))))
     v49 (:wat::holon::vector-bind (:wat::holon::encode (:wat::holon::leaf "role")) (:wat::holon::encode (:wat::holon::leaf "filler")))
     v50 (:wat::holon::vector-bundle (:wat::core::Vector :- [:wat::holon::Vector] (:wat::holon::encode (:wat::holon::leaf "role")) (:wat::holon::encode (:wat::holon::leaf "filler"))))
     v51 (:wat::holon::vector-blend (:wat::holon::encode (:wat::holon::leaf "role")) (:wat::holon::encode (:wat::holon::leaf "filler")) 0.7 0.3)
     v52 (:wat::holon::vector-permute (:wat::holon::encode (:wat::holon::leaf "role")) 1)
     v53 (:wat::holon::statement-length (:wat::holon::Bind (:wat::holon::leaf "role") (:wat::holon::leaf "filler")))
     v54 (:wat::holon::Hologram/get (:wat::holon::Hologram/make (:wat::core::fn [_x <- :wat::core::f64] -> :wat::core::bool true)) (:wat::holon::leaf "role"))
     v55 (:wat::holon::Hologram/find (:wat::holon::Hologram/make (:wat::core::fn [_x <- :wat::core::f64] -> :wat::core::bool true)) (:wat::holon::leaf "role"))
     v56 (:wat::holon::Hologram/len (:wat::holon::Hologram/make (:wat::core::fn [_x <- :wat::core::f64] -> :wat::core::bool true)))
     v57 (:wat::holon::Hologram/capacity (:wat::holon::Hologram/make (:wat::core::fn [_x <- :wat::core::f64] -> :wat::core::bool true)))
     v58 (:wat::holon::EngramLibrary/len (:wat::holon::EngramLibrary/new 4096))
     v59 (:wat::holon::EngramLibrary/contains (:wat::holon::EngramLibrary/new 4096) "anomaly-a")
     v60 (:wat::holon::EngramLibrary/names (:wat::holon::EngramLibrary/new 4096))
     v61 (:wat::holon::OnlineSubspace/dim (:wat::holon::OnlineSubspace/new 10000 8))
     v62 (:wat::holon::OnlineSubspace/k (:wat::holon::OnlineSubspace/new 10000 8))
     v63 (:wat::holon::OnlineSubspace/n (:wat::holon::OnlineSubspace/new 10000 8))
     v64 (:wat::holon::OnlineSubspace/threshold (:wat::holon::OnlineSubspace/new 10000 8))
     v65 (:wat::holon::OnlineSubspace/eigenvalues (:wat::holon::OnlineSubspace/new 10000 8))
     v66 (:wat::holon::OnlineSubspace/residual (:wat::holon::OnlineSubspace/new 10000 8) (:wat::holon::encode (:wat::holon::leaf "role")))
     v67 (:wat::holon::OnlineSubspace/project (:wat::holon::OnlineSubspace/new 10000 8) (:wat::holon::encode (:wat::holon::leaf "role")))
     v68 (:wat::holon::OnlineSubspace/reconstruct (:wat::holon::OnlineSubspace/new 10000 8) (:wat::holon::encode (:wat::holon::leaf "role")))
     v69 (:wat::holon::Reckoner/predict (:wat::holon::Reckoner/new-discrete "direction" 10000 100 (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "up") (:wat::holon::leaf "down"))) (:wat::holon::encode (:wat::holon::leaf "role")))
     v70 (:wat::holon::Reckoner/labels (:wat::holon::Reckoner/new-discrete "direction" 10000 100 (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "up") (:wat::holon::leaf "down"))))
     v71 (:wat::holon::Reckoner/dims (:wat::holon::Reckoner/new-discrete "direction" 10000 100 (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "up") (:wat::holon::leaf "down"))))
     v72 (:wat::core::match (:wat::holon::Bundle (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role") (:wat::holon::leaf "filler"))) ((:wat::core::Ok h) (:wat::holon::Bundle/children h)) (_ (:wat::holon::Bundle/children (:wat::holon::leaf "unreachable"))))
     v73 (:wat::core::match (:wat::holon::Bundle (:wat::core::Vector :- [:wat::holon::HolonAST] (:wat::holon::leaf "role") (:wat::holon::leaf "filler"))) ((:wat::core::Ok h) (:wat::holon::Bundle/first h)) (_ (:wat::holon::Bundle/first (:wat::holon::leaf "unreachable"))))
    ]
    (:wat::kernel::println "ALL 71 EXPRESSIONS EVALUATED WITHOUT ERROR")))
