;; probe-resolution.wat — arc 255.67, measure which of the 24 wat.type/ names resolve today.
(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::let
    [a (:wat::core::fn [x <- wat.type/i64] -> wat.type/i64 x)
     b (:wat::core::fn [x <- wat.type/f64] -> wat.type/f64 x)
     c (:wat::core::fn [x <- wat.type/u8] -> wat.type/u8 x)
     d (:wat::core::fn [x <- wat.type/bigint] -> wat.type/bigint x)
     e (:wat::core::fn [x <- wat.type/rational] -> wat.type/rational x)
     f (:wat::core::fn [x <- wat.type/char] -> wat.type/char x)
     g (:wat::core::fn [x <- wat.type/String] -> wat.type/String x)
     h (:wat::core::fn [x <- wat.type/bool] -> wat.type/bool x)
     i (:wat::core::fn [x <- wat.type/keyword] -> wat.type/keyword x)
     j (:wat::core::fn [x <- wat.type/Value] -> wat.type/Value x)
     k (:wat::core::fn [x <- wat.type/Fn] -> wat.type/Fn x)
     l (:wat::core::fn [x <- (wat.type/Vector :- [wat.type/i64])] -> (wat.type/Vector :- [wat.type/i64]) x)
     m (:wat::core::fn [x <- (wat.type/HashMap :- [wat.type/String wat.type/i64])] -> (wat.type/HashMap :- [wat.type/String wat.type/i64]) x)
     n (:wat::core::fn [x <- (wat.type/HashSet :- [wat.type/i64])] -> (wat.type/HashSet :- [wat.type/i64]) x)
     o (:wat::core::fn [x <- (wat.type/List :- [wat.type/i64])] -> (wat.type/List :- [wat.type/i64]) x)
     p (:wat::core::fn [x <- (wat.type/Tuple :- [wat.type/i64 wat.type/String])] -> (wat.type/Tuple :- [wat.type/i64 wat.type/String]) x)
     q (:wat::core::fn [x <- (wat.type/PersistentVector :- [wat.type/i64])] -> (wat.type/PersistentVector :- [wat.type/i64]) x)
     r (:wat::core::fn [x <- (wat.type/PersistentMap :- [wat.type/String wat.type/i64])] -> (wat.type/PersistentMap :- [wat.type/String wat.type/i64]) x)
     s (:wat::core::fn [x <- wat.type/Bytes] -> wat.type/Bytes x)
     t (:wat::core::fn [x <- wat.type/AST] -> wat.type/AST x)
     u (:wat::core::fn [x <- wat.type/nil] -> wat.type/nil x)]
    nil))
