//! Test home for `src/function/` namespaced home — fn-form preservation + error contracts.
//!
//! Established at Stone 241.18a per `feedback_namespaced_home_vigilia_gate`.
//! See `src/function/mod.rs` for the home's test-scope declaration including
//! cross-arc coverage references.
//!
//! Module list generated by build.rs into OUT_DIR (drop a .rs here → auto-compiled, no manual step).
include!(concat!(env!("OUT_DIR"), "/function_mods.rs"));
