(:wat::core::defn :user::pair-first :- [T] [a <- :T b <- :T] -> :T a)
(:wat::core::defn :user::probe-f02 [] -> :wat::core::i64 (:user::pair-first 1 2))
(:wat::core::defn :user::pair-first2 [a <- :T b <- :T] -> :T a)
(:wat::core::defn :user::probe-bare [] -> :wat::core::i64 (:user::pair-first2 1 2))
(:wat::core::defn :user::pair-two [a <- :T b <- :T] -> :T a)
(:wat::core::defn :user::probe-i64 [] -> :wat::core::i64 (:user::pair-two 1 2))
(:wat::core::defn :user::probe-bool [] -> :wat::core::bool (:user::pair-two true false))
