(:wat::core::defn :user::c01-sink [v <- (:wat::core::Vector :- [:wat::core::i64])] -> :wat::core::i64 0)
(:wat::core::defn :user::c01-pass [xs <- (wat.type/Vector :- [wat.type/i64])] -> :wat::core::i64 (:user::c01-sink xs))
(:wat::core::defn :user::c02-id [v <- (:wat::core::Vector :- [:wat::core::i64])] -> :wat::core::i64 0)
(:wat::core::typealias :user::IntVec (wat.type/Vector :- [wat.type/i64]))
(:wat::core::defn :user::c03-sink [v <- (:wat::core::Vector :- [:wat::core::i64])] -> :wat::core::i64 0)
(:wat::core::defn :user::c03-pass [xs <- :user::IntVec] -> :wat::core::i64 (:user::c03-sink xs))
