//! Integration test root for `src/comms/`.
//!
//! Tests organized to mirror src/ directory structure (convention started
//! 2026-05-19 with arc 214 Slice 3). The `mod.rs` root + sub-files pattern
//! is the idiomatic Rust way to group related integration tests:
//!
//!   - `tests/comms/mod.rs` is the crate root for the comms test binary
//!     (registered in Cargo.toml via a single `[[test]] name = "comms"
//!     path = "tests/comms/mod.rs"` entry)
//!   - the sub-files are brought in by build.rs (see below)
//!   - all comms tests share one binary (one link; one `#[ctor]` init)
//!   - filter via `cargo test --test comms <path>::` — e.g.,
//!     `cargo test --test comms thread::` runs only thread-tier tests
//!
//! Adding a group: `tests/<group>/mod.rs` (this `include!` stub) + one
//! `[[test]]` Cargo.toml entry. Adding a test to a group: just drop the `.rs`
//! file in — build.rs lists it automatically; there is no mod list to edit.
//!
//! The module list is GENERATED by build.rs into OUT_DIR — drop a `.rs` here and
//! it is compiled + run on the next `cargo test`; no manual step, no drift gate.
include!(concat!(env!("OUT_DIR"), "/comms_mods.rs"));
