//! Test home for `src/macros/` — behavior-named tests (arc lineage in git, not filenames).
//! Module list generated by build.rs into OUT_DIR (drop a .rs here → auto-compiled, no manual step).
//! Run: cargo test --release -p wat --test macros
include!(concat!(env!("OUT_DIR"), "/macros_mods.rs"));
