//! Excursus 003 strike C, GC1 — no tracked `.edn` golden holds a `#wat.runtime/ValueSnapshot`
//! map carrying a `:provenance` key.
//!
//! `AUDIT-the-shape-of-an-error.md` F5: `provenance` was `Unknown`/absent at 503 of 506
//! `ValueSnapshot` construction sites — written on the wire as `:provenance nil` (22 goldens)
//! or `Option.None` (19 goldens), real in only 5. The 2026-09-27 ruling item 4 ("`provenance`
//! goes") removed the field from the Rust struct (`src/value/observe.rs`), its writer
//! (`value_snapshot_to_edn`, `src/edn/error.rs`), `to_record`'s builder
//! (`src/value/runtime_records.rs`) and the wat declaration (`wat/runtime-errors.wat`) — this
//! gate is the standing proof that no golden regresses the field back onto the wire.
//!
//! Scoped to `ValueSnapshot` specifically (tag namespace `wat.runtime`, name `ValueSnapshot`),
//! NOT every `:provenance` key anywhere — a different record could coincidentally use the same
//! field name for something else, and that would not be this defect. **Parse, never grep**, same
//! discipline as `no_causes_key_in_golden_files.rs` / `no_double_quoted_edn_in_golden_files.rs`:
//! this walks the parsed DATA and only flags `:provenance` sitting as a map key inside a
//! `Tagged` value whose tag is exactly `#wat.runtime/ValueSnapshot`.
//!
//! Scope matches the brief's own measurement and the sibling lints: `git ls-files '*.edn'`, no
//! exclusions.
//!
//! Anchor: measured directly against this strike's own pre-recapture tree (HEAD `5756d8832`,
//! before this strike's commit) via `git grep ':provenance' -- 'tests/*.edn'`: 46 occurrences
//! across 44 files, matching audit F5's 22 (`nil`) + 19 (`Option.None`) + 5 (real) = 46 exactly.
//! Every occurrence sampled (one from each of the three categories, plus the full
//! `probe_ex003_hashability_looks_inside`/`probe_diagnostic_value_snapshot_in_errors` families)
//! sits inside a `#wat.runtime/ValueSnapshot` map — none is a same-named field on an unrelated
//! record. This gate runs GREEN post-recapture (0 files) — the dynamic RED proof is the
//! mutation below, not a re-run against the old corpus (recapturing would un-fix the very
//! goldens this strike just landed).
//!
//! Mutation (recorded in the strike report, not re-encoded here as a second, permanently
//! mutated copy): same subtlety `no_causes_key_in_golden_files.rs` documents — this gate parses
//! committed FILES, not live writer behavior, so reverting `value_snapshot_to_edn` alone does
//! NOT redden it (no golden is regenerated by running it); the provable mutation is injecting
//! `:provenance nil` into one committed `#wat.runtime/ValueSnapshot` map (simulating a bad
//! recapture landing against a reverted writer) — driven: RED, naming that exact file and a
//! count of 1.

use std::path::Path;
use wat_edn::{OwnedValue, Value};

fn git_ls_files(root: &str, glob: &str) -> Vec<String> {
    let out = std::process::Command::new("git")
        .args(["-C", root, "ls-files", "--", glob])
        .output()
        .expect("git ls-files");
    assert!(out.status.success(), "git ls-files must succeed");
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .map(str::to_string)
        .collect()
}

/// Recursively collect every occurrence of a `:provenance` KEYWORD sitting as a MAP KEY
/// inside a `Tagged` value whose tag is exactly `wat.runtime/ValueSnapshot`, at any depth
/// (nested inside any list/vector/set/map/tagged-body element).
fn find_value_snapshot_provenance_keys(v: &OwnedValue, out: &mut usize) {
    match v {
        Value::Tagged(tag, inner) => {
            let is_value_snapshot = tag.namespace() == "wat.runtime" && tag.name() == "ValueSnapshot";
            if is_value_snapshot {
                if let Value::Map(entries) = &**inner {
                    for (k, _) in entries {
                        if matches!(k, Value::Keyword(kw) if kw.name() == "provenance" && kw.namespace().is_none())
                        {
                            *out += 1;
                        }
                    }
                }
            }
            find_value_snapshot_provenance_keys(inner, out);
        }
        Value::Map(entries) => {
            for (k, val) in entries {
                find_value_snapshot_provenance_keys(k, out);
                find_value_snapshot_provenance_keys(val, out);
            }
        }
        Value::List(xs) | Value::Vector(xs) | Value::Set(xs) => {
            for x in xs {
                find_value_snapshot_provenance_keys(x, out);
            }
        }
        _ => {}
    }
}

#[test]
fn no_edn_golden_value_snapshot_carries_a_provenance_key() {
    let root = env!("CARGO_MANIFEST_DIR");
    let paths = git_ls_files(root, "*.edn");
    // NON-VACUITY: the tracked `.edn` corpus is large; a count this low means
    // `git ls-files` itself broke, or the corpus was deleted out from under this wall.
    assert!(
        paths.len() > 100,
        "expected the tracked .edn corpus; got {}",
        paths.len()
    );

    let mut violations: Vec<(String, usize)> = Vec::new();
    let mut unparseable = 0usize;
    for rel in &paths {
        let full = Path::new(root).join(rel);
        let src = std::fs::read_to_string(&full).unwrap_or_else(|e| panic!("{rel}: read: {e}"));
        let trimmed = src.trim();
        if trimmed.is_empty() {
            continue;
        }
        // A handful of goldens are TEMPLATES (an unquoted `{PLACEHOLDER}` stands in for a
        // value substituted at comparison time) and do not parse raw — out of this gate's
        // reach, same carve-out the sibling lints document.
        let parsed = match wat_edn::parse_owned(trimmed) {
            Ok(v) => v,
            Err(_) => {
                unparseable += 1;
                continue;
            }
        };
        let mut count = 0usize;
        find_value_snapshot_provenance_keys(&parsed, &mut count);
        if count > 0 {
            violations.push((rel.clone(), count));
        }
    }

    eprintln!("{unparseable} of {} tracked .edn files skipped (unquoted template placeholder)", paths.len());
    // NON-VACUITY on the skip count: if parsing collapsed wholesale, this gate would
    // silently check nothing and stay green.
    assert!(
        unparseable < paths.len() / 2,
        "{unparseable} of {} tracked .edn files did not parse at all — far more than the \
         template-placeholder shape this gate expects; `wat_edn::parse_owned` may be broken, \
         which would make every skip above silent",
        paths.len()
    );

    let total: usize = violations.iter().map(|(_, n)| n).sum();
    assert!(
        violations.is_empty(),
        "{} golden .edn file(s) ({} :provenance key(s) total) still carry `:provenance` inside a \
         `#wat.runtime/ValueSnapshot` map — excursus 003 strike C removed the field (F5, ruling \
         2026-09-27 item 4). Recapture with `UPDATE_EDN=1 cargo nextest run --release`, and read \
         every diff — the only allowed change is the `:provenance …` line leaving `ValueSnapshot` \
         maps (plus, where the dropped value was real, the message's own `(built by …)`/`(from …)`/\
         `(bound from …)` suffix, which came from the same field's Display rendering):\n  {}",
        violations.len(),
        total,
        violations.iter().map(|(f, n)| format!("{f} ({n})")).collect::<Vec<_>>().join("\n  ")
    );
}
