//! tests/nursery/ — the living test commons (arc 252 test-surface reorg).
//!
//! NOT an archive. This is where tests are RAISED and PROVEN, then GRADUATE to
//! their permanent `src/<home>` test dir (`tests/comms/`, `tests/value/`, …) when
//! a home is warranted. It is the default home for a test that belongs to no single
//! src-home yet, and the place iterative test-development accumulates.
//!
//! The contract (builder, 2026-06-06):
//!   - Accumulate HONESTLY-NAMED good tests here as you go — every test real,
//!     every assertion meaningful (no sentinels).
//!   - Arc/stone/probe-numbered names (`probe_arc216_stone1_hashset_roundtrip`) are
//!     VALID — they are real, they pass, they are useful. Improve a name when
//!     warranted (especially on graduation to a home), not for its own sake.
//!   - PROMOTE a test OUT to `tests/<home>/` (with a behavior name) when it clearly
//!     belongs to one src-home. The nursery raises; the homes keep.
//!
//! One leak-safe `[[test]]` binary (Cargo: `name="nursery"`). Keep only PURE
//! (non-process) tests here so `cargo test --test nursery` never leaks; process
//! tests live in their home group (`tests/comms/`), leak-`#[ignore]`'d as needed.
//!
//! The module list is GENERATED by build.rs into OUT_DIR — drop a `.rs` file here
//! and it is compiled + run on the next `cargo test`. There is no mod list to
//! hand-edit and no drift gate to forget: a test can never be silently lost.
//!
//! Run: `cargo test --release -p wat --test nursery`
include!(concat!(env!("OUT_DIR"), "/nursery_mods.rs"));
